/*
 * File: app/store/AuditTypeStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ifeng.store.AuditTypeStore', {
    extend: 'Ext.data.Store',
    alias: 'store.auditTypeStore',

    requires: [
        'ifeng.model.AuditType',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'ifeng.model.AuditType',
            storeId: 'AuditTypeStore',
            data: [
                {
                    name: '播放次数',
                    value: 0
                },
                {
                    name: '用户访问数',
                    value: 1
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'array'
                }
            }
        }, cfg)]);
    }
});