/*
 * File: app/view/GlobalConstantForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ifeng.view.GlobalConstantForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.constantForm',
    layout: 'form',
    id: '_constantForm',
    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],
    height: '100%',
    
    bodyPadding: 10,
    collapsed: false,
    collapsible: true,
    title: 'Global Constant',
    defaults: {
    	labelAlign: 'right',
    },
    buttonAlign: 'center',
    items: [{
    	title: 'Global',
        xtype: 'fieldset',
        contentEl: 'global-div',
        collapsible: true,
        collapsed: true
    	/*defaults: {
    		labelAlign: 'right'
    	},
    	items: [{
    		xtype: 'textfield',
    		anchor: '100%',
    		fieldLabel: 'HDFS URL'
    	},{
    		xtype: 'textfield',
    		anchor: '100%',
    		fieldLabel: 'Web HDFS URL'
    	}]*/
    },{
    	xtype: 'fieldset',
    	/*defaults: {
    		labelAlign: 'right'
    	},*/
    	collapsible: true,
    	title: 'HDFS',
    	contentEl: 'hdfs-div'
    	/*items: [{
    		xtype: 'textfield',
    		anchor: '100%',
    		fieldLabel: 'HDFS URL',
    		name: 'url',
    		emptyText: 'Hadoop REST 服务URL, 默认为 http://114.80.177.144:50070/'
    	},{
    		xtype: 'textfield',
    		anchor: '100%',
    		fieldLabel: 'Web HDFS URL',
    		name: 'webUrl',
    		emptyText: 'Hadoop REST 默认操作, webhdfs/v1/?op=LISTSTATUS.'
    	},{
    		xtype: 'textfield',
    		anchor: '100%',
    		fieldLabel: 'Label',
    		empty: ''
    	}]*/
    },{
    	xtype: 'fieldset',
    	/*defaults: {
    		labelAlign: 'right'
    	},*/
    	collapsible: true,
    	title: 'IPServer',
    	contentEl: 'ipserver-div'
    	/*items: [{
    		xtype: 'textfield',
    		anchor: '100%',
    		fieldLabel: 'IPServer URL',
    		emptyText: 'IPServer的URL地址,默认值为 http://123.103.58.182/ipbase/ipserver/ipArea'
    	},{
    		xtype: 'textfield',
    		anchor: '100%',
    		fieldLabel: 'File Location',
    		emptyText: 'IPArea txt 文件本地存储目录, 默认为 /home/cloudland/app_data/ipArea.txt.'
    	}]*/
    }],
    buttons: [{
    	text: '立即生效',
    	iconCls: 'icon-search',
    	action: 'doRefresh'
    },{
    	text: '重启后生效',
    	iconCls: 'icon-cancel',
    	action: 'doRereshLater'
    },{
    	text: '取消',
    	iconCls: 'icon-cancel',
    	action: 'doReset'
    }],

    initComponent: function() {
        var me = this;
        Ext.applyIf(me, {
        	
        });

        me.callParent(arguments);
    }

});